# Copyright 2022 Caleb Magruder

name: Build and Test

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install cpplint
        run: pip install cpplint

      - name: Install cppcheck
        run: brew install cppcheck

      - name: Create Build Directory
        run: cmake -E make_directory build

      - name: CMake Configure
        working-directory: build/
        run: cmake $GITHUB_WORKSPACE
      
      - name: CMake Build
        working-directory: build
        run: cmake --build .
      
      - name: CTest
        working-directory: build
        run: ctest --output-on-failure
