# Copyright 2022 Caleb Magruder

name: Release Package
permissions:
  contents: write

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Create Build Directory
        run: cmake -E make_directory build

      - name: CMake Configure
        working-directory: build/
        run: cmake $GITHUB_WORKSPACE

      - name: CMake Build
        working-directory: build
        run: cmake --build . --target JSON_package

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: true
          prerelease: true

